Hw02 express
vladdubrovskyi/nodejs-homework-rest-api pull request #1
Opened 2023-01-07 18:14 UTC by vladdubrovskyi

Добрий вечір. Прохання перевірити. Дякую!

2023-01-07 20:10 UTC, KhYulian commented on controllers/controllers.js
> +const contactsDataBase = require("../models/contacts");
зробіть деструктуризацію

2023-01-07 20:10 UTC, KhYulian commented on controllers/controllers.js
> +  }
для цього використовуйте Joi

2023-01-07 20:11 UTC, KhYulian commented on helpers/index.js
> +
використовуйте класи

2023-01-07 20:11 UTC, KhYulian commented on routes/api/contacts.js
> +});
Виенсіть const  ContactSchema в окремий файл

2023-01-07 20:12 UTC, KhYulian commented on routes/api/contacts.js
> +  validateBody(ContactSchema),
створіть окрему Joi схему для оновлення контакту

2023-01-07 20:12 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-07 20:12 UTC, KhYulian commented
Відповідайте на коменти по мірі виправлення :)

2023-01-08 10:18 UTC, vladdubrovskyi commented on controllers/controllers.js
> +const contactsDataBase = require("../models/contacts");
Готово

2023-01-08 10:18 UTC, vladdubrovskyi commented on routes/api/contacts.js
> +});
Готово

2023-01-08 10:46 UTC, vladdubrovskyi commented on routes/api/contacts.js
> +  validateBody(ContactSchema),
Готово

2023-01-08 10:46 UTC, vladdubrovskyi commented on controllers/controllers.js
> +  }
Готово

2023-01-08 18:00 UTC, vladdubrovskyi commented on helpers/index.js
> +
готово

2023-01-08 18:54 UTC, KhYulian commented on helpers/index.js
> +}
дуже сумнівна практика. Що заважає просто написати  throw new MyError(message, status)  де потрібно

2023-01-08 18:54 UTC, KhYulian commented on controllers/controllers.js
> +    return next(hanldeError("not found", 404));
hanldeError - не використовуйте

2023-01-08 18:55 UTC, KhYulian commented on schema/schema.js
> +  .required()
.required() для оновлення не потрібен. Достатньо min(1)

2023-01-08 18:56 UTC, KhYulian commented on helpers/index.js
> +}
якщо використовуте MyError, то ця функ. вам вже не потрібна

2023-01-08 19:08 UTC, vladdubrovskyi commented on helpers/index.js
> +}
Виправив

2023-01-08 19:08 UTC, vladdubrovskyi commented on controllers/controllers.js
> +    return next(hanldeError("not found", 404));
Готово

2023-01-08 19:08 UTC, vladdubrovskyi commented on schema/schema.js
> +  .required()
Виправив

2023-01-08 19:08 UTC, vladdubrovskyi commented on helpers/index.js
> +}
Видалив

2023-01-08 19:22 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-08 19:22 UTC, merged